global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['172.18.0.9:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['172.18.0.10:9100']
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['172.18.0.12:9113']

